version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: nfc-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from nfc-vl.ru --to nfc-site:10002
    networks:
      - nfc-network

networks:
  nfc-network:
    external: true
    name: nfc-site_default

volumes:
  caddy_data:
  caddy_config:

